set(CTEST_PROJECT_NAME "PVTOL")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "home")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=PVTOL")
set(CTEST_DROP_SITE_CDASH TRUE)
